### ISSUE TITLE
Broken link for "Web"  https://github.com/Azure-Samples/blockchain/tree/master/blockchain-development-kit/connect/web 

### ISSUE THREAD

**Issue by amrikmahal** [Azure-Samples/blockchain-devkit#5]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> 404 error when one navigates to url https://github.com/Azure-Samples/blockchain/tree/master/blockchain-development-kit/connect/web

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by cnsegura** [comment]
Hi amrikmahal - can you tell me where/what sample you find this link and we'll update it appropriately: Correct link is https://github.com/Azure-Samples/blockchain-devkit/tree/master/connect/web

**Comment by amrikmahal** [comment]
Sorry, Its been almost a month and i cannot recall what i was browsing. I tried to poking around, but could not find the source of the broken url.

**Comment by cnsegura** [comment]
Thanks amrikmahal, sorry for the delay in responding. I'll close this bug at this time, but if you do find the error later feel free to reopen. All URLs have moved 

from ./Azure-Samples/Blockchain/tree/master/blockchain-development-kit/<dir>/<subdir> 

to: ./Azure-Samples/blockchain-devkit/tree/master/<dir>/<subdir>
