### ISSUE TITLE
Links not working in devops PDF docs

### ISSUE THREAD

**Issue by rstuven** [Azure-Samples/blockchain-devkit#6]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Open the PDF files in the `devops` directory in Chrome PDF viewer or Acrobat Reader.
> Try to follow the links.

### Any log messages given by the failure
> None.

### Expected/desired behavior
> To be able to follow the links, like in the source docx files where they are working fine.

### OS and Version?
> macOS Mojave.

### Versions
> 

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by cnsegura** [comment]
thanks rstuven - fixed
