### ISSUE TITLE
Dead Link In Accelerator

### ISSUE THREAD

**Issue by opticyclic** [Azure-Samples/blockchain-devkit#9]
The README at https://github.com/Azure-Samples/blockchain-devkit/blob/master/accelerators/corda/cordapps/basic-provenance/README.md has a dead link to a png that 404s.

https://www.corda.net/wp-content/uploads/2016/11/fg005_corda_b.png

**Comment by cnsegura** [comment]
Hi Opticyclic - perhaps there was a network issue when you filed this issue - both the png, and the URL that is linked in the README both resolve for me.

**Comment by opticyclic** [comment]
Actually, what has happened is that a redirect has been put in place.
That url now resolves to https://www.corda.net/wp-content/uploads/2019/11/fg005_corda_b.png (note the year in the url has changed from 2016 to 2019)
